# Generated by Django 4.0.1 on 2022-01-11 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0002_alter_category_options_photo_add_date_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='photo',
            options={'ordering': ['-add_date']},
        ),
        migrations.AlterField(
            model_name='photo',
            name='add_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
